changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - chore
        - maintenance
    - title: Other Changes
      labels:
        - "*"
